'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VBEuchre4.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose this option if you want Clubs to be trump.  You will need to win three tricks in the hand or else be &quot;euchred&quot; (the opposing team will get two points if that happens)..
        '''</summary>
        Friend ReadOnly Property BID_Clubs() As String
            Get
                Return ResourceManager.GetString("BID_Clubs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose this option if you want Diamonds to be trump.  You will need to win three tricks in the hand or else be &quot;euchred&quot; (the opposing team will get two points if that happens)..
        '''</summary>
        Friend ReadOnly Property BID_Diamonds() As String
            Get
                Return ResourceManager.GetString("BID_Diamonds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose this option if you want to play this hand without your partner&apos;s help.  If you take all five tricks, you will get four points. (If the &quot;Quiet Dealer&quot; option is being used in this game and your partner is the dealer, then this option is automatically selected for you and cannot be changed.).
        '''</summary>
        Friend ReadOnly Property BID_GoingAlone() As String
            Get
                Return ResourceManager.GetString("BID_GoingAlone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose this option if you want Hearts to be trump.  You will need to win three tricks in the hand or else be &quot;euchred&quot; (the opposing team will get two points if that happens)..
        '''</summary>
        Friend ReadOnly Property BID_Hearts() As String
            Get
                Return ResourceManager.GetString("BID_Hearts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose the option if you do not want the dealer pick up the upturned card and have its suit be trump..
        '''</summary>
        Friend ReadOnly Property BID_Pass1() As String
            Get
                Return ResourceManager.GetString("BID_Pass1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose this option if you do not want to call trump..
        '''</summary>
        Friend ReadOnly Property BID_Pass2() As String
            Get
                Return ResourceManager.GetString("BID_Pass2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose this option if you want the dealer to pick up the upturned card in the kitty and have its suit be trump.  You will need to win three tricks in the hand or else be &quot;euchred&quot; (the opposing team will get two points if that happens)..
        '''</summary>
        Friend ReadOnly Property BID_PickItUp() As String
            Get
                Return ResourceManager.GetString("BID_PickItUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose this option if you want Spades to be trump.  You will need to win three tricks in the hand or else be &quot;euchred&quot; (the opposing team will get two points if that happens)..
        '''</summary>
        Friend ReadOnly Property BID_Spades() As String
            Get
                Return ResourceManager.GetString("BID_Spades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDBACK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDBACK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEAceOfClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEAceOfClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEAceOfDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEAceOfDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEAceOfHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEAceOfHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEAceOfSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEAceOfSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEFiveOfClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEFiveOfClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEFiveOfDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEFiveOfDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEFiveOfHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEFiveOfHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEFiveOfSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEFiveOfSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEJackOfClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEJackOfClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEJackOfDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEJackOfDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEJackOfHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEJackOfHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEJackOfSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEJackOfSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEKingOfClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEKingOfClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEKingOfDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEKingOfDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEKingOfHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEKingOfHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEKingOfSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEKingOfSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACENineOfClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACENineOfClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACENineOfDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACENineOfDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACENineOfHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACENineOfHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACENineOfSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACENineOfSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEQueenOfClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEQueenOfClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEQueenOfDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEQueenOfDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEQueenOfHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEQueenOfHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACEQueenOfSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACEQueenOfSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACETenOfClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACETenOfClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACETenOfDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACETenOfDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACETenOfHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACETenOfHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARDFACETenOfSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARDFACETenOfSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ace of Clubs.
        '''</summary>
        Friend ReadOnly Property CARDNAME_AceOfClubs() As String
            Get
                Return ResourceManager.GetString("CARDNAME_AceOfClubs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ace of Diamonds.
        '''</summary>
        Friend ReadOnly Property CARDNAME_AceOfDiamonds() As String
            Get
                Return ResourceManager.GetString("CARDNAME_AceOfDiamonds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ace of Hearts.
        '''</summary>
        Friend ReadOnly Property CARDNAME_AceOfHearts() As String
            Get
                Return ResourceManager.GetString("CARDNAME_AceOfHearts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ace of Spades.
        '''</summary>
        Friend ReadOnly Property CARDNAME_AceOfSpades() As String
            Get
                Return ResourceManager.GetString("CARDNAME_AceOfSpades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Face-down card].
        '''</summary>
        Friend ReadOnly Property CARDNAME_BACK() As String
            Get
                Return ResourceManager.GetString("CARDNAME_BACK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jack of Clubs.
        '''</summary>
        Friend ReadOnly Property CARDNAME_JackOfClubs() As String
            Get
                Return ResourceManager.GetString("CARDNAME_JackOfClubs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jack of Diamonds.
        '''</summary>
        Friend ReadOnly Property CARDNAME_JackOfDiamonds() As String
            Get
                Return ResourceManager.GetString("CARDNAME_JackOfDiamonds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jack of Hearts.
        '''</summary>
        Friend ReadOnly Property CARDNAME_JackOfHearts() As String
            Get
                Return ResourceManager.GetString("CARDNAME_JackOfHearts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jack of Spades.
        '''</summary>
        Friend ReadOnly Property CARDNAME_JackOfSpades() As String
            Get
                Return ResourceManager.GetString("CARDNAME_JackOfSpades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to King of Clubs.
        '''</summary>
        Friend ReadOnly Property CARDNAME_KingOfClubs() As String
            Get
                Return ResourceManager.GetString("CARDNAME_KingOfClubs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to King of Diamonds.
        '''</summary>
        Friend ReadOnly Property CARDNAME_KingOfDiamonds() As String
            Get
                Return ResourceManager.GetString("CARDNAME_KingOfDiamonds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to King of Hearts.
        '''</summary>
        Friend ReadOnly Property CARDNAME_KingOfHearts() As String
            Get
                Return ResourceManager.GetString("CARDNAME_KingOfHearts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to King of Spades.
        '''</summary>
        Friend ReadOnly Property CARDNAME_KingOfSpades() As String
            Get
                Return ResourceManager.GetString("CARDNAME_KingOfSpades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Left Bower.
        '''</summary>
        Friend ReadOnly Property CARDNAME_LeftBower() As String
            Get
                Return ResourceManager.GetString("CARDNAME_LeftBower", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nine of Clubs.
        '''</summary>
        Friend ReadOnly Property CARDNAME_NineOfClubs() As String
            Get
                Return ResourceManager.GetString("CARDNAME_NineOfClubs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nine of Diamonds.
        '''</summary>
        Friend ReadOnly Property CARDNAME_NineOfDiamonds() As String
            Get
                Return ResourceManager.GetString("CARDNAME_NineOfDiamonds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nine of Hearts.
        '''</summary>
        Friend ReadOnly Property CARDNAME_NineOfHearts() As String
            Get
                Return ResourceManager.GetString("CARDNAME_NineOfHearts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nine of Spades.
        '''</summary>
        Friend ReadOnly Property CARDNAME_NineOfSpades() As String
            Get
                Return ResourceManager.GetString("CARDNAME_NineOfSpades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Queen of Clubs.
        '''</summary>
        Friend ReadOnly Property CARDNAME_QueenOfClubs() As String
            Get
                Return ResourceManager.GetString("CARDNAME_QueenOfClubs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Queen of Diamonds.
        '''</summary>
        Friend ReadOnly Property CARDNAME_QueenOfDiamonds() As String
            Get
                Return ResourceManager.GetString("CARDNAME_QueenOfDiamonds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Queen of Hearts.
        '''</summary>
        Friend ReadOnly Property CARDNAME_QueenOfHearts() As String
            Get
                Return ResourceManager.GetString("CARDNAME_QueenOfHearts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Queen of Spades.
        '''</summary>
        Friend ReadOnly Property CARDNAME_QueenOfSpades() As String
            Get
                Return ResourceManager.GetString("CARDNAME_QueenOfSpades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Right Bower.
        '''</summary>
        Friend ReadOnly Property CARDNAME_RightBower() As String
            Get
                Return ResourceManager.GetString("CARDNAME_RightBower", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ten of Clubs.
        '''</summary>
        Friend ReadOnly Property CARDNAME_TenOfClubs() As String
            Get
                Return ResourceManager.GetString("CARDNAME_TenOfClubs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ten of Diamonds.
        '''</summary>
        Friend ReadOnly Property CARDNAME_TenOfDiamonds() As String
            Get
                Return ResourceManager.GetString("CARDNAME_TenOfDiamonds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ten of Hearts.
        '''</summary>
        Friend ReadOnly Property CARDNAME_TenOfHearts() As String
            Get
                Return ResourceManager.GetString("CARDNAME_TenOfHearts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ten of Spades.
        '''</summary>
        Friend ReadOnly Property CARDNAME_TenOfSpades() As String
            Get
                Return ResourceManager.GetString("CARDNAME_TenOfSpades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clubs.
        '''</summary>
        Friend ReadOnly Property CLUBS() As String
            Get
                Return ResourceManager.GetString("CLUBS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CLUBSIMAGE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLUBSIMAGE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to exit?.
        '''</summary>
        Friend ReadOnly Property Command_Exit() As String
            Get
                Return ResourceManager.GetString("Command_Exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit VBEuchre.
        '''</summary>
        Friend ReadOnly Property Command_ExitTitle() As String
            Get
                Return ResourceManager.GetString("Command_ExitTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to start a new game?.
        '''</summary>
        Friend ReadOnly Property Command_New() As String
            Get
                Return ResourceManager.GetString("Command_New", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Game.
        '''</summary>
        Friend ReadOnly Property Command_NewTitle() As String
            Get
                Return ResourceManager.GetString("Command_NewTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diamonds.
        '''</summary>
        Friend ReadOnly Property DIAMONDS() As String
            Get
                Return ResourceManager.GetString("DIAMONDS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DIAMONDSIMAGE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIAMONDSIMAGE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Euchre() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Euchre", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Their Score: {0}.
        '''</summary>
        Friend ReadOnly Property Format_TheirScore() As String
            Get
                Return ResourceManager.GetString("Format_TheirScore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Their Tricks Taken: {0}.
        '''</summary>
        Friend ReadOnly Property Format_TheirTricks() As String
            Get
                Return ResourceManager.GetString("Format_TheirTricks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your Score: {0}.
        '''</summary>
        Friend ReadOnly Property Format_YourScore() As String
            Get
                Return ResourceManager.GetString("Format_YourScore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your Tricks Taken: {0}.
        '''</summary>
        Friend ReadOnly Property Format_YourTricks() As String
            Get
                Return ResourceManager.GetString("Format_YourTricks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hearts.
        '''</summary>
        Friend ReadOnly Property HEARTS() As String
            Get
                Return ResourceManager.GetString("HEARTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HEARTSIMAGE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HEARTSIMAGE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (no suit).
        '''</summary>
        Friend ReadOnly Property NOSUIT() As String
            Get
                Return ResourceManager.GetString("NOSUIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NOSUITIMAGE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NOSUITIMAGE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All players passed twice. Deal passes to the next player..
        '''</summary>
        Friend ReadOnly Property Notice_AllPassedTwice() As String
            Get
                Return ResourceManager.GetString("Notice_AllPassedTwice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selecting dealer (first Jack wins deal)....
        '''</summary>
        Friend ReadOnly Property Notice_ChoosingDealer() As String
            Get
                Return ResourceManager.GetString("Notice_ChoosingDealer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} says &quot;Trump is {1}.&quot;.
        '''</summary>
        Friend ReadOnly Property Notice_ChoseTrump() As String
            Get
                Return ResourceManager.GetString("Notice_ChoseTrump", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} says &quot;Trump is {1} -- I&apos;m going alone!&quot;.
        '''</summary>
        Friend ReadOnly Property Notice_ChoseTrumpAlone() As String
            Get
                Return ResourceManager.GetString("Notice_ChoseTrumpAlone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dealing the cards....
        '''</summary>
        Friend ReadOnly Property Notice_DealingCards() As String
            Get
                Return ResourceManager.GetString("Notice_DealingCards", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} was dealt the {1}..
        '''</summary>
        Friend ReadOnly Property Notice_DealtACard() As String
            Get
                Return ResourceManager.GetString("Notice_DealtACard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} wins the deal!.
        '''</summary>
        Friend ReadOnly Property Notice_IAmTheDealer() As String
            Get
                Return ResourceManager.GetString("Notice_IAmTheDealer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} says &quot;I&apos;ll pick it up.&quot; Trump is {1}..
        '''</summary>
        Friend ReadOnly Property Notice_IPickItUp() As String
            Get
                Return ResourceManager.GetString("Notice_IPickItUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} says &quot;I&apos;ll pick it up -- I&apos;m going alone!&quot; Trump is {1}..
        '''</summary>
        Friend ReadOnly Property Notice_IPickItUpAlone() As String
            Get
                Return ResourceManager.GetString("Notice_IPickItUpAlone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The {0} was turned up in the kitty..
        '''</summary>
        Friend ReadOnly Property Notice_KittyCard() As String
            Get
                Return ResourceManager.GetString("Notice_KittyCard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} says &quot;I pass.&quot;.
        '''</summary>
        Friend ReadOnly Property Notice_Pass() As String
            Get
                Return ResourceManager.GetString("Notice_Pass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} says &quot;Pick it up.&quot;  Trump is {1}..
        '''</summary>
        Friend ReadOnly Property Notice_PickItUp() As String
            Get
                Return ResourceManager.GetString("Notice_PickItUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} says &quot;Pick it up -- I&apos;m going alone!&quot; Trump is {1}..
        '''</summary>
        Friend ReadOnly Property Notice_PickItUpAlone() As String
            Get
                Return ResourceManager.GetString("Notice_PickItUpAlone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select a card to play..
        '''</summary>
        Friend ReadOnly Property Notice_PlayACard() As String
            Get
                Return ResourceManager.GetString("Notice_PlayACard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} played the {1}..
        '''</summary>
        Friend ReadOnly Property Notice_PlayedACard() As String
            Get
                Return ResourceManager.GetString("Notice_PlayedACard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shuffling the cards....
        '''</summary>
        Friend ReadOnly Property Notice_ShufflingCards() As String
            Get
                Return ResourceManager.GetString("Notice_ShufflingCards", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting new game....
        '''</summary>
        Friend ReadOnly Property Notice_StartingNewGame() As String
            Get
                Return ResourceManager.GetString("Notice_StartingNewGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select a card to drop..
        '''</summary>
        Friend ReadOnly Property Notice_SwapACard() As String
            Get
                Return ResourceManager.GetString("Notice_SwapACard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Their team took the trick..
        '''</summary>
        Friend ReadOnly Property Notice_TheirTeamWonTrick() As String
            Get
                Return ResourceManager.GetString("Notice_TheirTeamWonTrick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Their team euchred your team for two points!.
        '''</summary>
        Friend ReadOnly Property Notice_TheyEuchredYou() As String
            Get
                Return ResourceManager.GetString("Notice_TheyEuchredYou", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Their team super-euchred your team for four points!.
        '''</summary>
        Friend ReadOnly Property Notice_TheySuperEuchredYou() As String
            Get
                Return ResourceManager.GetString("Notice_TheySuperEuchredYou", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Their team won the game!.
        '''</summary>
        Friend ReadOnly Property Notice_TheyWonTheGame() As String
            Get
                Return ResourceManager.GetString("Notice_TheyWonTheGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Their team won the hand for one point..
        '''</summary>
        Friend ReadOnly Property Notice_TheyWonTheHand() As String
            Get
                Return ResourceManager.GetString("Notice_TheyWonTheHand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Their team took all of the tricks for two points!.
        '''</summary>
        Friend ReadOnly Property Notice_TheyWonTheHandAllTricks() As String
            Get
                Return ResourceManager.GetString("Notice_TheyWonTheHandAllTricks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Their team took all of the tricks, going alone, for four points!.
        '''</summary>
        Friend ReadOnly Property Notice_TheyWonTheHandAllTricksAlone() As String
            Get
                Return ResourceManager.GetString("Notice_TheyWonTheHandAllTricksAlone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Welcome to VB Euchre! Choose &quot;New Game&quot; from the VBEuchre menu (or press F2) to start a new game..
        '''</summary>
        Friend ReadOnly Property Notice_Welcome() As String
            Get
                Return ResourceManager.GetString("Notice_Welcome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your team euchred their team for two points!.
        '''</summary>
        Friend ReadOnly Property Notice_YouEuchredThem() As String
            Get
                Return ResourceManager.GetString("Notice_YouEuchredThem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your team took the trick..
        '''</summary>
        Friend ReadOnly Property Notice_YourTeamWonTrick() As String
            Get
                Return ResourceManager.GetString("Notice_YourTeamWonTrick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your team super-euchred their team for four points!.
        '''</summary>
        Friend ReadOnly Property Notice_YouSuperEuchredThem() As String
            Get
                Return ResourceManager.GetString("Notice_YouSuperEuchredThem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your team won the game!.
        '''</summary>
        Friend ReadOnly Property Notice_YouWonTheGame() As String
            Get
                Return ResourceManager.GetString("Notice_YouWonTheGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your team won the hand for one point..
        '''</summary>
        Friend ReadOnly Property Notice_YouWonTheHand() As String
            Get
                Return ResourceManager.GetString("Notice_YouWonTheHand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your team won all the tricks for two points!.
        '''</summary>
        Friend ReadOnly Property Notice_YouWonTheHandAllTricks() As String
            Get
                Return ResourceManager.GetString("Notice_YouWonTheHandAllTricks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your team won all of the tricks, going alone, for four points!.
        '''</summary>
        Friend ReadOnly Property Notice_YouWonTheHandAllTricksAlone() As String
            Get
                Return ResourceManager.GetString("Notice_YouWonTheHandAllTricksAlone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If &quot;Conservative&quot; is selected, this player will tend to select trump only if winning the hand is guaranteed..
        '''</summary>
        Friend ReadOnly Property OPTION_Conservative() As String
            Get
                Return ResourceManager.GetString("OPTION_Conservative", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If &quot;Crazy&quot; is selected, this player will tend to select trump on hard-to-make hands..
        '''</summary>
        Friend ReadOnly Property OPTION_Crazy() As String
            Get
                Return ResourceManager.GetString("OPTION_Crazy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specify a name for the player on your left here..
        '''</summary>
        Friend ReadOnly Property OPTION_LeftOpponent() As String
            Get
                Return ResourceManager.GetString("OPTION_LeftOpponent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specify a voice for your left opponent here..
        '''</summary>
        Friend ReadOnly Property OPTION_LeftOpponentVoice() As String
            Get
                Return ResourceManager.GetString("OPTION_LeftOpponentVoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specify a name for yourself here..
        '''</summary>
        Friend ReadOnly Property OPTION_Name() As String
            Get
                Return ResourceManager.GetString("OPTION_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking this box will remove all of the cards of rank nine from the deck except the Nine of Hearts.  (This is a variant rule used in the Appalachian area.).
        '''</summary>
        Friend ReadOnly Property OPTION_NineOfHearts() As String
            Get
                Return ResourceManager.GetString("OPTION_NineOfHearts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If &quot;Normal&quot; is selected, this player will tend to select trump only when there is a reasonable chance of winning at least three tricks..
        '''</summary>
        Friend ReadOnly Property OPTION_Normal() As String
            Get
                Return ResourceManager.GetString("OPTION_Normal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking this box means that you will be able to see all card hands (plus the kitty), instead of just your own cards. This is a useful option for when you&apos;re learning how to play the game..
        '''</summary>
        Friend ReadOnly Property OPTION_PeekAtOtherCards() As String
            Get
                Return ResourceManager.GetString("OPTION_PeekAtOtherCards", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking this box means that the dealer&apos;s partner has to &quot;go alone&quot; if he or she selects the trump suit..
        '''</summary>
        Friend ReadOnly Property OPTION_QuietDealer() As String
            Get
                Return ResourceManager.GetString("OPTION_QuietDealer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specify a name for the player on your right here..
        '''</summary>
        Friend ReadOnly Property OPTION_RightOpponent() As String
            Get
                Return ResourceManager.GetString("OPTION_RightOpponent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specify a voice for your right opponent here..
        '''</summary>
        Friend ReadOnly Property OPTION_RightOpponentVoice() As String
            Get
                Return ResourceManager.GetString("OPTION_RightOpponentVoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking this box means that you&apos;ll hear sound effects during the game. (Game play is slightly quicker if this is turned off.).
        '''</summary>
        Friend ReadOnly Property OPTION_SoundEffects() As String
            Get
                Return ResourceManager.GetString("OPTION_SoundEffects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking this box will force the dealer to select the trump suit on the second round if no one else has called trump.  The dealer&apos;s team will need to win three tricks or else be euchred, as usual..
        '''</summary>
        Friend ReadOnly Property OPTION_StickTheDealer() As String
            Get
                Return ResourceManager.GetString("OPTION_StickTheDealer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking this box means that, if the calling teams loses all five tricks, the opposing team will get 4 points instead of 2 points..
        '''</summary>
        Friend ReadOnly Property OPTION_SuperEuchre() As String
            Get
                Return ResourceManager.GetString("OPTION_SuperEuchre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specify a name for your partner here..
        '''</summary>
        Friend ReadOnly Property OPTION_YourPartner() As String
            Get
                Return ResourceManager.GetString("OPTION_YourPartner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specify a voice for your partner here..
        '''</summary>
        Friend ReadOnly Property OPTION_YourPartnerVoice() As String
            Get
                Return ResourceManager.GetString("OPTION_YourPartnerVoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The opponent on your left.
        '''</summary>
        Friend ReadOnly Property Player_LeftOpponent() As String
            Get
                Return ResourceManager.GetString("Player_LeftOpponent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}&apos;s partner.
        '''</summary>
        Friend ReadOnly Property Player_Partner() As String
            Get
                Return ResourceManager.GetString("Player_Partner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The player.
        '''</summary>
        Friend ReadOnly Property Player_Player() As String
            Get
                Return ResourceManager.GetString("Player_Player", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The opponent on your right.
        '''</summary>
        Friend ReadOnly Property Player_RightOpponent() As String
            Get
                Return ResourceManager.GetString("Player_RightOpponent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to and i&apos;m going alone..
        '''</summary>
        Friend ReadOnly Property SAY_Alone() As String
            Get
                Return ResourceManager.GetString("SAY_Alone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to trump is clubs..
        '''</summary>
        Friend ReadOnly Property SAY_Clubs() As String
            Get
                Return ResourceManager.GetString("SAY_Clubs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to trump is diamonds..
        '''</summary>
        Friend ReadOnly Property SAY_Diamonds() As String
            Get
                Return ResourceManager.GetString("SAY_Diamonds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to trump is hearts..
        '''</summary>
        Friend ReadOnly Property SAY_Hearts() As String
            Get
                Return ResourceManager.GetString("SAY_Hearts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to i&apos;ll pick it up..
        '''</summary>
        Friend ReadOnly Property SAY_IPickItUp() As String
            Get
                Return ResourceManager.GetString("SAY_IPickItUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to lets play euchre.
        '''</summary>
        Friend ReadOnly Property SAY_LetsPlayEuchre() As String
            Get
                Return ResourceManager.GetString("SAY_LetsPlayEuchre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to looks like i got some good cards that time {0}.
        '''</summary>
        Friend ReadOnly Property SAY_MeGotFour() As String
            Get
                Return ResourceManager.GetString("SAY_MeGotFour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to one point for us {0}.
        '''</summary>
        Friend ReadOnly Property SAY_MeGotOne() As String
            Get
                Return ResourceManager.GetString("SAY_MeGotOne", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to guess i made a good call that time, huh {0}.
        '''</summary>
        Friend ReadOnly Property SAY_MeGotTwo() As String
            Get
                Return ResourceManager.GetString("SAY_MeGotTwo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to i pass..
        '''</summary>
        Friend ReadOnly Property SAY_Pass() As String
            Get
                Return ResourceManager.GetString("SAY_Pass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pick it up!.
        '''</summary>
        Friend ReadOnly Property SAY_PickItUp() As String
            Get
                Return ResourceManager.GetString("SAY_PickItUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to trump is spades..
        '''</summary>
        Friend ReadOnly Property SAY_Spades() As String
            Get
                Return ResourceManager.GetString("SAY_Spades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to oh, man, they got the loner!.
        '''</summary>
        Friend ReadOnly Property SAY_TheyGotFour() As String
            Get
                Return ResourceManager.GetString("SAY_TheyGotFour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to drat, one point for them..
        '''</summary>
        Friend ReadOnly Property SAY_TheyGotOne() As String
            Get
                Return ResourceManager.GetString("SAY_TheyGotOne", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rats, they picked up all of the tricks..
        '''</summary>
        Friend ReadOnly Property SAY_TheyGotTwo() As String
            Get
                Return ResourceManager.GetString("SAY_TheyGotTwo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to oh well, nice try {0}.  Shall we have another go?.
        '''</summary>
        Friend ReadOnly Property SAY_TheyWon() As String
            Get
                Return ResourceManager.GetString("SAY_TheyWon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to all right {0}, we set them!.
        '''</summary>
        Friend ReadOnly Property SAY_WeEuchredThem() As String
            Get
                Return ResourceManager.GetString("SAY_WeEuchredThem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sorry, i guess i messed up on that one {0}..
        '''</summary>
        Friend ReadOnly Property SAY_WeGotEuchredMyFault() As String
            Get
                Return ResourceManager.GetString("SAY_WeGotEuchredMyFault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rats, guess i was just not much help {0}..
        '''</summary>
        Friend ReadOnly Property SAY_WeGotEuchredOurFault() As String
            Get
                Return ResourceManager.GetString("SAY_WeGotEuchredOurFault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to you just might want some help from me next time on that sort of hand {0}..
        '''</summary>
        Friend ReadOnly Property SAY_WeGotEuchredYourFault() As String
            Get
                Return ResourceManager.GetString("SAY_WeGotEuchredYourFault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to way to go!  guess you didn&apos;t need my help {0}..
        '''</summary>
        Friend ReadOnly Property SAY_WeGotFour() As String
            Get
                Return ResourceManager.GetString("SAY_WeGotFour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to nice job {0}!.
        '''</summary>
        Friend ReadOnly Property SAY_WeGotOne() As String
            Get
                Return ResourceManager.GetString("SAY_WeGotOne", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to great job {0}!.
        '''</summary>
        Friend ReadOnly Property SAY_WeGotTwo() As String
            Get
                Return ResourceManager.GetString("SAY_WeGotTwo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to way to go {0}, we gave them the old super euchre!.
        '''</summary>
        Friend ReadOnly Property SAY_WeSuperEuchredThem() As String
            Get
                Return ResourceManager.GetString("SAY_WeSuperEuchredThem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to great game {0}!  Shall we play again?.
        '''</summary>
        Friend ReadOnly Property SAY_WeWon() As String
            Get
                Return ResourceManager.GetString("SAY_WeWon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREThem0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREThem0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREThem1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREThem1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREThem10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREThem10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREThem2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREThem2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREThem3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREThem3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREThem4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREThem4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREThem5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREThem5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREThem6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREThem6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREThem7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREThem7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREThem8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREThem8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREThem9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREThem9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREUs0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREUs0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREUs1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREUs1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREUs10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREUs10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREUs2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREUs2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREUs3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREUs3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREUs4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREUs4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREUs5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREUs5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREUs6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREUs6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREUs7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREUs7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREUs8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREUs8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCOREUs9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCOREUs9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SoundApplauseLoud() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SoundApplauseLoud", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SoundApplauseSoft() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SoundApplauseSoft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SoundApplauseWild() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SoundApplauseWild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SoundPlayCard() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SoundPlayCard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SoundShuffleDeck() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SoundShuffleDeck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spades.
        '''</summary>
        Friend ReadOnly Property SPADES() As String
            Get
                Return ResourceManager.GetString("SPADES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SPADESIMAGE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SPADESIMAGE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman{\*\falt Times New Roman};}
        '''{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial{\*\falt Helvetica};}{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 050501020107060 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property VBEuchreRules() As String
            Get
                Return ResourceManager.GetString("VBEuchreRules", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
