//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSEuchre4.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSEuchre4.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this option if you want Clubs to be trump.  You will need to win three tricks in the hand or else be &quot;euchred&quot; (the opposing team will get two points if that happens)..
        /// </summary>
        internal static string BID_Clubs {
            get {
                return ResourceManager.GetString("BID_Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this option if you want Diamonds to be trump.  You will need to win three tricks in the hand or else be &quot;euchred&quot; (the opposing team will get two points if that happens)..
        /// </summary>
        internal static string BID_Diamonds {
            get {
                return ResourceManager.GetString("BID_Diamonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this option if you want to play this hand without your partner&apos;s help.  If you take all five tricks, you will get four points. (If the &quot;Quiet Dealer&quot; option is being used in this game and your partner is the dealer, then this option is automatically selected for you and cannot be changed.).
        /// </summary>
        internal static string BID_GoingAlone {
            get {
                return ResourceManager.GetString("BID_GoingAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this option if you want Hearts to be trump.  You will need to win three tricks in the hand or else be &quot;euchred&quot; (the opposing team will get two points if that happens)..
        /// </summary>
        internal static string BID_Hearts {
            get {
                return ResourceManager.GetString("BID_Hearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the option if you do not want the dealer pick up the upturned card and have its suit be trump..
        /// </summary>
        internal static string BID_Pass1 {
            get {
                return ResourceManager.GetString("BID_Pass1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this option if you do not want to call trump..
        /// </summary>
        internal static string BID_Pass2 {
            get {
                return ResourceManager.GetString("BID_Pass2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this option if you want the dealer to pick up the upturned card in the kitty and have its suit be trump.  You will need to win three tricks in the hand or else be &quot;euchred&quot; (the opposing team will get two points if that happens)..
        /// </summary>
        internal static string BID_PickItUp {
            get {
                return ResourceManager.GetString("BID_PickItUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this option if you want Spades to be trump.  You will need to win three tricks in the hand or else be &quot;euchred&quot; (the opposing team will get two points if that happens)..
        /// </summary>
        internal static string BID_Spades {
            get {
                return ResourceManager.GetString("BID_Spades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDBACK {
            get {
                object obj = ResourceManager.GetObject("CARDBACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEAceOfClubs {
            get {
                object obj = ResourceManager.GetObject("CARDFACEAceOfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEAceOfDiamonds {
            get {
                object obj = ResourceManager.GetObject("CARDFACEAceOfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEAceOfHearts {
            get {
                object obj = ResourceManager.GetObject("CARDFACEAceOfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEAceOfSpades {
            get {
                object obj = ResourceManager.GetObject("CARDFACEAceOfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEFiveOfClubs {
            get {
                object obj = ResourceManager.GetObject("CARDFACEFiveOfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEFiveOfDiamonds {
            get {
                object obj = ResourceManager.GetObject("CARDFACEFiveOfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEFiveOfHearts {
            get {
                object obj = ResourceManager.GetObject("CARDFACEFiveOfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEFiveOfSpades {
            get {
                object obj = ResourceManager.GetObject("CARDFACEFiveOfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEJackOfClubs {
            get {
                object obj = ResourceManager.GetObject("CARDFACEJackOfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEJackOfDiamonds {
            get {
                object obj = ResourceManager.GetObject("CARDFACEJackOfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEJackOfHearts {
            get {
                object obj = ResourceManager.GetObject("CARDFACEJackOfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEJackOfSpades {
            get {
                object obj = ResourceManager.GetObject("CARDFACEJackOfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEKingOfClubs {
            get {
                object obj = ResourceManager.GetObject("CARDFACEKingOfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEKingOfDiamonds {
            get {
                object obj = ResourceManager.GetObject("CARDFACEKingOfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEKingOfHearts {
            get {
                object obj = ResourceManager.GetObject("CARDFACEKingOfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEKingOfSpades {
            get {
                object obj = ResourceManager.GetObject("CARDFACEKingOfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACENineOfClubs {
            get {
                object obj = ResourceManager.GetObject("CARDFACENineOfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACENineOfDiamonds {
            get {
                object obj = ResourceManager.GetObject("CARDFACENineOfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACENineOfHearts {
            get {
                object obj = ResourceManager.GetObject("CARDFACENineOfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACENineOfSpades {
            get {
                object obj = ResourceManager.GetObject("CARDFACENineOfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEQueenOfClubs {
            get {
                object obj = ResourceManager.GetObject("CARDFACEQueenOfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEQueenOfDiamonds {
            get {
                object obj = ResourceManager.GetObject("CARDFACEQueenOfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEQueenOfHearts {
            get {
                object obj = ResourceManager.GetObject("CARDFACEQueenOfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACEQueenOfSpades {
            get {
                object obj = ResourceManager.GetObject("CARDFACEQueenOfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACETenOfClubs {
            get {
                object obj = ResourceManager.GetObject("CARDFACETenOfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACETenOfDiamonds {
            get {
                object obj = ResourceManager.GetObject("CARDFACETenOfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACETenOfHearts {
            get {
                object obj = ResourceManager.GetObject("CARDFACETenOfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARDFACETenOfSpades {
            get {
                object obj = ResourceManager.GetObject("CARDFACETenOfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ace of Clubs.
        /// </summary>
        internal static string CARDNAME_AceOfClubs {
            get {
                return ResourceManager.GetString("CARDNAME_AceOfClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ace of Diamonds.
        /// </summary>
        internal static string CARDNAME_AceOfDiamonds {
            get {
                return ResourceManager.GetString("CARDNAME_AceOfDiamonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ace of Hearts.
        /// </summary>
        internal static string CARDNAME_AceOfHearts {
            get {
                return ResourceManager.GetString("CARDNAME_AceOfHearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ace of Spades.
        /// </summary>
        internal static string CARDNAME_AceOfSpades {
            get {
                return ResourceManager.GetString("CARDNAME_AceOfSpades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Face-down card].
        /// </summary>
        internal static string CARDNAME_BACK {
            get {
                return ResourceManager.GetString("CARDNAME_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jack of Clubs.
        /// </summary>
        internal static string CARDNAME_JackOfClubs {
            get {
                return ResourceManager.GetString("CARDNAME_JackOfClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jack of Diamonds.
        /// </summary>
        internal static string CARDNAME_JackOfDiamonds {
            get {
                return ResourceManager.GetString("CARDNAME_JackOfDiamonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jack of Hearts.
        /// </summary>
        internal static string CARDNAME_JackOfHearts {
            get {
                return ResourceManager.GetString("CARDNAME_JackOfHearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jack of Spades.
        /// </summary>
        internal static string CARDNAME_JackOfSpades {
            get {
                return ResourceManager.GetString("CARDNAME_JackOfSpades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King of Clubs.
        /// </summary>
        internal static string CARDNAME_KingOfClubs {
            get {
                return ResourceManager.GetString("CARDNAME_KingOfClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King of Diamonds.
        /// </summary>
        internal static string CARDNAME_KingOfDiamonds {
            get {
                return ResourceManager.GetString("CARDNAME_KingOfDiamonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King of Hearts.
        /// </summary>
        internal static string CARDNAME_KingOfHearts {
            get {
                return ResourceManager.GetString("CARDNAME_KingOfHearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King of Spades.
        /// </summary>
        internal static string CARDNAME_KingOfSpades {
            get {
                return ResourceManager.GetString("CARDNAME_KingOfSpades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Bower.
        /// </summary>
        internal static string CARDNAME_LeftBower {
            get {
                return ResourceManager.GetString("CARDNAME_LeftBower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine of Clubs.
        /// </summary>
        internal static string CARDNAME_NineOfClubs {
            get {
                return ResourceManager.GetString("CARDNAME_NineOfClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine of Diamonds.
        /// </summary>
        internal static string CARDNAME_NineOfDiamonds {
            get {
                return ResourceManager.GetString("CARDNAME_NineOfDiamonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine of Hearts.
        /// </summary>
        internal static string CARDNAME_NineOfHearts {
            get {
                return ResourceManager.GetString("CARDNAME_NineOfHearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine of Spades.
        /// </summary>
        internal static string CARDNAME_NineOfSpades {
            get {
                return ResourceManager.GetString("CARDNAME_NineOfSpades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen of Clubs.
        /// </summary>
        internal static string CARDNAME_QueenOfClubs {
            get {
                return ResourceManager.GetString("CARDNAME_QueenOfClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen of Diamonds.
        /// </summary>
        internal static string CARDNAME_QueenOfDiamonds {
            get {
                return ResourceManager.GetString("CARDNAME_QueenOfDiamonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen of Hearts.
        /// </summary>
        internal static string CARDNAME_QueenOfHearts {
            get {
                return ResourceManager.GetString("CARDNAME_QueenOfHearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen of Spades.
        /// </summary>
        internal static string CARDNAME_QueenOfSpades {
            get {
                return ResourceManager.GetString("CARDNAME_QueenOfSpades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Bower.
        /// </summary>
        internal static string CARDNAME_RightBower {
            get {
                return ResourceManager.GetString("CARDNAME_RightBower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten of Clubs.
        /// </summary>
        internal static string CARDNAME_TenOfClubs {
            get {
                return ResourceManager.GetString("CARDNAME_TenOfClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten of Diamonds.
        /// </summary>
        internal static string CARDNAME_TenOfDiamonds {
            get {
                return ResourceManager.GetString("CARDNAME_TenOfDiamonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten of Hearts.
        /// </summary>
        internal static string CARDNAME_TenOfHearts {
            get {
                return ResourceManager.GetString("CARDNAME_TenOfHearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten of Spades.
        /// </summary>
        internal static string CARDNAME_TenOfSpades {
            get {
                return ResourceManager.GetString("CARDNAME_TenOfSpades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs.
        /// </summary>
        internal static string CLUBS {
            get {
                return ResourceManager.GetString("CLUBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CLUBSIMAGE {
            get {
                object obj = ResourceManager.GetObject("CLUBSIMAGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string Command_Exit {
            get {
                return ResourceManager.GetString("Command_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit C#Euchre.
        /// </summary>
        internal static string Command_ExitTitle {
            get {
                return ResourceManager.GetString("Command_ExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to start a new game?.
        /// </summary>
        internal static string Command_New {
            get {
                return ResourceManager.GetString("Command_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string Command_NewTitle {
            get {
                return ResourceManager.GetString("Command_NewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman{\*\falt Times New Roman};}
        ///{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial{\*\falt Helvetica};}{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 050501020107060 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSEuchreRules {
            get {
                return ResourceManager.GetString("CSEuchreRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamonds.
        /// </summary>
        internal static string DIAMONDS {
            get {
                return ResourceManager.GetString("DIAMONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DIAMONDSIMAGE {
            get {
                object obj = ResourceManager.GetObject("DIAMONDSIMAGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Euchre {
            get {
                object obj = ResourceManager.GetObject("Euchre", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Their Score: {0}.
        /// </summary>
        internal static string Format_TheirScore {
            get {
                return ResourceManager.GetString("Format_TheirScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Their Tricks Taken: {0}.
        /// </summary>
        internal static string Format_TheirTricks {
            get {
                return ResourceManager.GetString("Format_TheirTricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Score: {0}.
        /// </summary>
        internal static string Format_YourScore {
            get {
                return ResourceManager.GetString("Format_YourScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Tricks Taken: {0}.
        /// </summary>
        internal static string Format_YourTricks {
            get {
                return ResourceManager.GetString("Format_YourTricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearts.
        /// </summary>
        internal static string HEARTS {
            get {
                return ResourceManager.GetString("HEARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HEARTSIMAGE {
            get {
                object obj = ResourceManager.GetObject("HEARTSIMAGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no suit).
        /// </summary>
        internal static string NOSUIT {
            get {
                return ResourceManager.GetString("NOSUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NOSUITIMAGE {
            get {
                object obj = ResourceManager.GetObject("NOSUITIMAGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All players passed twice. Deal passes to the next player..
        /// </summary>
        internal static string Notice_AllPassedTwice {
            get {
                return ResourceManager.GetString("Notice_AllPassedTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting dealer (first Jack wins deal)....
        /// </summary>
        internal static string Notice_ChoosingDealer {
            get {
                return ResourceManager.GetString("Notice_ChoosingDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} says &quot;Trump is {1}.&quot;.
        /// </summary>
        internal static string Notice_ChoseTrump {
            get {
                return ResourceManager.GetString("Notice_ChoseTrump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} says &quot;Trump is {1} -- I&apos;m going alone!&quot;.
        /// </summary>
        internal static string Notice_ChoseTrumpAlone {
            get {
                return ResourceManager.GetString("Notice_ChoseTrumpAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealing the cards....
        /// </summary>
        internal static string Notice_DealingCards {
            get {
                return ResourceManager.GetString("Notice_DealingCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was dealt the {1}..
        /// </summary>
        internal static string Notice_DealtACard {
            get {
                return ResourceManager.GetString("Notice_DealtACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wins the deal!.
        /// </summary>
        internal static string Notice_IAmTheDealer {
            get {
                return ResourceManager.GetString("Notice_IAmTheDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} says &quot;I&apos;ll pick it up.&quot; Trump is {1}..
        /// </summary>
        internal static string Notice_IPickItUp {
            get {
                return ResourceManager.GetString("Notice_IPickItUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} says &quot;I&apos;ll pick it up -- I&apos;m going alone!&quot; Trump is {1}..
        /// </summary>
        internal static string Notice_IPickItUpAlone {
            get {
                return ResourceManager.GetString("Notice_IPickItUpAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} was turned up in the kitty..
        /// </summary>
        internal static string Notice_KittyCard {
            get {
                return ResourceManager.GetString("Notice_KittyCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} says &quot;I pass.&quot;.
        /// </summary>
        internal static string Notice_Pass {
            get {
                return ResourceManager.GetString("Notice_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} says &quot;Pick it up.&quot;  Trump is {1}..
        /// </summary>
        internal static string Notice_PickItUp {
            get {
                return ResourceManager.GetString("Notice_PickItUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} says &quot;Pick it up -- I&apos;m going alone!&quot; Trump is {1}..
        /// </summary>
        internal static string Notice_PickItUpAlone {
            get {
                return ResourceManager.GetString("Notice_PickItUpAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a card to play..
        /// </summary>
        internal static string Notice_PlayACard {
            get {
                return ResourceManager.GetString("Notice_PlayACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} played the {1}..
        /// </summary>
        internal static string Notice_PlayedACard {
            get {
                return ResourceManager.GetString("Notice_PlayedACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffling the cards....
        /// </summary>
        internal static string Notice_ShufflingCards {
            get {
                return ResourceManager.GetString("Notice_ShufflingCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting new game....
        /// </summary>
        internal static string Notice_StartingNewGame {
            get {
                return ResourceManager.GetString("Notice_StartingNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a card to drop..
        /// </summary>
        internal static string Notice_SwapACard {
            get {
                return ResourceManager.GetString("Notice_SwapACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Their team took the trick..
        /// </summary>
        internal static string Notice_TheirTeamWonTrick {
            get {
                return ResourceManager.GetString("Notice_TheirTeamWonTrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Their team euchred your team for two points!.
        /// </summary>
        internal static string Notice_TheyEuchredYou {
            get {
                return ResourceManager.GetString("Notice_TheyEuchredYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Their team super-euchred your team for four points!.
        /// </summary>
        internal static string Notice_TheySuperEuchredYou {
            get {
                return ResourceManager.GetString("Notice_TheySuperEuchredYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Their team won the game!.
        /// </summary>
        internal static string Notice_TheyWonTheGame {
            get {
                return ResourceManager.GetString("Notice_TheyWonTheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Their team won the hand for one point..
        /// </summary>
        internal static string Notice_TheyWonTheHand {
            get {
                return ResourceManager.GetString("Notice_TheyWonTheHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Their team took all of the tricks for two points!.
        /// </summary>
        internal static string Notice_TheyWonTheHandAllTricks {
            get {
                return ResourceManager.GetString("Notice_TheyWonTheHandAllTricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Their team took all of the tricks, going alone, for four points!.
        /// </summary>
        internal static string Notice_TheyWonTheHandAllTricksAlone {
            get {
                return ResourceManager.GetString("Notice_TheyWonTheHandAllTricksAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to C#Euchre! Choose &quot;New Game&quot; from the C#Euchre menu (or press F2) to start a new game..
        /// </summary>
        internal static string Notice_Welcome {
            get {
                return ResourceManager.GetString("Notice_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team euchred their team for two points!.
        /// </summary>
        internal static string Notice_YouEuchredThem {
            get {
                return ResourceManager.GetString("Notice_YouEuchredThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team took the trick..
        /// </summary>
        internal static string Notice_YourTeamWonTrick {
            get {
                return ResourceManager.GetString("Notice_YourTeamWonTrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team super-euchred their team for four points!.
        /// </summary>
        internal static string Notice_YouSuperEuchredThem {
            get {
                return ResourceManager.GetString("Notice_YouSuperEuchredThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team won the game!.
        /// </summary>
        internal static string Notice_YouWonTheGame {
            get {
                return ResourceManager.GetString("Notice_YouWonTheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team won the hand for one point..
        /// </summary>
        internal static string Notice_YouWonTheHand {
            get {
                return ResourceManager.GetString("Notice_YouWonTheHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team won all the tricks for two points!.
        /// </summary>
        internal static string Notice_YouWonTheHandAllTricks {
            get {
                return ResourceManager.GetString("Notice_YouWonTheHandAllTricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team won all of the tricks, going alone, for four points!.
        /// </summary>
        internal static string Notice_YouWonTheHandAllTricksAlone {
            get {
                return ResourceManager.GetString("Notice_YouWonTheHandAllTricksAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If &quot;Conservative&quot; is selected, this player will tend to select trump only if winning the hand is guaranteed..
        /// </summary>
        internal static string OPTION_Conservative {
            get {
                return ResourceManager.GetString("OPTION_Conservative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If &quot;Crazy&quot; is selected, this player will tend to select trump on hard-to-make hands..
        /// </summary>
        internal static string OPTION_Crazy {
            get {
                return ResourceManager.GetString("OPTION_Crazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a name for the player on your left here..
        /// </summary>
        internal static string OPTION_LeftOpponent {
            get {
                return ResourceManager.GetString("OPTION_LeftOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a voice for your left opponent here..
        /// </summary>
        internal static string OPTION_LeftOpponentVoice {
            get {
                return ResourceManager.GetString("OPTION_LeftOpponentVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a name for yourself here..
        /// </summary>
        internal static string OPTION_Name {
            get {
                return ResourceManager.GetString("OPTION_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking this box will remove all of the cards of rank nine from the deck except the Nine of Hearts.  (This is a variant rule used in the Appalachian area.).
        /// </summary>
        internal static string OPTION_NineOfHearts {
            get {
                return ResourceManager.GetString("OPTION_NineOfHearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If &quot;Normal&quot; is selected, this player will tend to select trump only when there is a reasonable chance of winning at least three tricks..
        /// </summary>
        internal static string OPTION_Normal {
            get {
                return ResourceManager.GetString("OPTION_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking this box means that you will be able to see all card hands (plus the kitty), instead of just your own cards. This is a useful option for when you&apos;re learning how to play the game..
        /// </summary>
        internal static string OPTION_PeekAtOtherCards {
            get {
                return ResourceManager.GetString("OPTION_PeekAtOtherCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking this box means that the dealer&apos;s partner has to &quot;go alone&quot; if he or she selects the trump suit..
        /// </summary>
        internal static string OPTION_QuietDealer {
            get {
                return ResourceManager.GetString("OPTION_QuietDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a name for the player on your right here..
        /// </summary>
        internal static string OPTION_RightOpponent {
            get {
                return ResourceManager.GetString("OPTION_RightOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a voice for your right opponent here..
        /// </summary>
        internal static string OPTION_RightOpponentVoice {
            get {
                return ResourceManager.GetString("OPTION_RightOpponentVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking this box means that you&apos;ll hear sound effects during the game. (Game play is slightly quicker if this is turned off.).
        /// </summary>
        internal static string OPTION_SoundEffects {
            get {
                return ResourceManager.GetString("OPTION_SoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking this box will force the dealer to select the trump suit on the second round if no one else has called trump.  The dealer&apos;s team will need to win three tricks or else be euchred, as usual..
        /// </summary>
        internal static string OPTION_StickTheDealer {
            get {
                return ResourceManager.GetString("OPTION_StickTheDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking this box means that, if the calling teams loses all five tricks, the opposing team will get 4 points instead of 2 points..
        /// </summary>
        internal static string OPTION_SuperEuchre {
            get {
                return ResourceManager.GetString("OPTION_SuperEuchre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a name for your partner here..
        /// </summary>
        internal static string OPTION_YourPartner {
            get {
                return ResourceManager.GetString("OPTION_YourPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a voice for your partner here..
        /// </summary>
        internal static string OPTION_YourPartnerVoice {
            get {
                return ResourceManager.GetString("OPTION_YourPartnerVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opponent on your left.
        /// </summary>
        internal static string Player_LeftOpponent {
            get {
                return ResourceManager.GetString("Player_LeftOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s partner.
        /// </summary>
        internal static string Player_Partner {
            get {
                return ResourceManager.GetString("Player_Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player.
        /// </summary>
        internal static string Player_Player {
            get {
                return ResourceManager.GetString("Player_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opponent on your right.
        /// </summary>
        internal static string Player_RightOpponent {
            get {
                return ResourceManager.GetString("Player_RightOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and i&apos;m going alone..
        /// </summary>
        internal static string SAY_Alone {
            get {
                return ResourceManager.GetString("SAY_Alone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trump is clubs..
        /// </summary>
        internal static string SAY_Clubs {
            get {
                return ResourceManager.GetString("SAY_Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trump is diamonds..
        /// </summary>
        internal static string SAY_Diamonds {
            get {
                return ResourceManager.GetString("SAY_Diamonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trump is hearts..
        /// </summary>
        internal static string SAY_Hearts {
            get {
                return ResourceManager.GetString("SAY_Hearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i&apos;ll pick it up..
        /// </summary>
        internal static string SAY_IPickItUp {
            get {
                return ResourceManager.GetString("SAY_IPickItUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lets play euchre.
        /// </summary>
        internal static string SAY_LetsPlayEuchre {
            get {
                return ResourceManager.GetString("SAY_LetsPlayEuchre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looks like i got some good cards that time {0}.
        /// </summary>
        internal static string SAY_MeGotFour {
            get {
                return ResourceManager.GetString("SAY_MeGotFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one point for us {0}.
        /// </summary>
        internal static string SAY_MeGotOne {
            get {
                return ResourceManager.GetString("SAY_MeGotOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guess i made a good call that time, huh {0}.
        /// </summary>
        internal static string SAY_MeGotTwo {
            get {
                return ResourceManager.GetString("SAY_MeGotTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i pass..
        /// </summary>
        internal static string SAY_Pass {
            get {
                return ResourceManager.GetString("SAY_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pick it up!.
        /// </summary>
        internal static string SAY_PickItUp {
            get {
                return ResourceManager.GetString("SAY_PickItUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trump is spades..
        /// </summary>
        internal static string SAY_Spades {
            get {
                return ResourceManager.GetString("SAY_Spades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oh, man, they got the loner!.
        /// </summary>
        internal static string SAY_TheyGotFour {
            get {
                return ResourceManager.GetString("SAY_TheyGotFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drat, one point for them..
        /// </summary>
        internal static string SAY_TheyGotOne {
            get {
                return ResourceManager.GetString("SAY_TheyGotOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rats, they picked up all of the tricks..
        /// </summary>
        internal static string SAY_TheyGotTwo {
            get {
                return ResourceManager.GetString("SAY_TheyGotTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oh well, nice try {0}.  Shall we have another go?.
        /// </summary>
        internal static string SAY_TheyWon {
            get {
                return ResourceManager.GetString("SAY_TheyWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all right {0}, we set them!.
        /// </summary>
        internal static string SAY_WeEuchredThem {
            get {
                return ResourceManager.GetString("SAY_WeEuchredThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, i guess i messed up on that one {0}..
        /// </summary>
        internal static string SAY_WeGotEuchredMyFault {
            get {
                return ResourceManager.GetString("SAY_WeGotEuchredMyFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rats, guess i was just not much help {0}..
        /// </summary>
        internal static string SAY_WeGotEuchredOurFault {
            get {
                return ResourceManager.GetString("SAY_WeGotEuchredOurFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you just might want some help from me next time on that sort of hand {0}..
        /// </summary>
        internal static string SAY_WeGotEuchredYourFault {
            get {
                return ResourceManager.GetString("SAY_WeGotEuchredYourFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to way to go!  guess you didn&apos;t need my help {0}..
        /// </summary>
        internal static string SAY_WeGotFour {
            get {
                return ResourceManager.GetString("SAY_WeGotFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nice job {0}!.
        /// </summary>
        internal static string SAY_WeGotOne {
            get {
                return ResourceManager.GetString("SAY_WeGotOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to great job {0}!.
        /// </summary>
        internal static string SAY_WeGotTwo {
            get {
                return ResourceManager.GetString("SAY_WeGotTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to way to go {0}, we gave them the old super euchre!.
        /// </summary>
        internal static string SAY_WeSuperEuchredThem {
            get {
                return ResourceManager.GetString("SAY_WeSuperEuchredThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to great game {0}!  Shall we play again?.
        /// </summary>
        internal static string SAY_WeWon {
            get {
                return ResourceManager.GetString("SAY_WeWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREThem0 {
            get {
                object obj = ResourceManager.GetObject("SCOREThem0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREThem1 {
            get {
                object obj = ResourceManager.GetObject("SCOREThem1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREThem10 {
            get {
                object obj = ResourceManager.GetObject("SCOREThem10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREThem2 {
            get {
                object obj = ResourceManager.GetObject("SCOREThem2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREThem3 {
            get {
                object obj = ResourceManager.GetObject("SCOREThem3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREThem4 {
            get {
                object obj = ResourceManager.GetObject("SCOREThem4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREThem5 {
            get {
                object obj = ResourceManager.GetObject("SCOREThem5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREThem6 {
            get {
                object obj = ResourceManager.GetObject("SCOREThem6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREThem7 {
            get {
                object obj = ResourceManager.GetObject("SCOREThem7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREThem8 {
            get {
                object obj = ResourceManager.GetObject("SCOREThem8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREThem9 {
            get {
                object obj = ResourceManager.GetObject("SCOREThem9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREUs0 {
            get {
                object obj = ResourceManager.GetObject("SCOREUs0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREUs1 {
            get {
                object obj = ResourceManager.GetObject("SCOREUs1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREUs10 {
            get {
                object obj = ResourceManager.GetObject("SCOREUs10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREUs2 {
            get {
                object obj = ResourceManager.GetObject("SCOREUs2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREUs3 {
            get {
                object obj = ResourceManager.GetObject("SCOREUs3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREUs4 {
            get {
                object obj = ResourceManager.GetObject("SCOREUs4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREUs5 {
            get {
                object obj = ResourceManager.GetObject("SCOREUs5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREUs6 {
            get {
                object obj = ResourceManager.GetObject("SCOREUs6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREUs7 {
            get {
                object obj = ResourceManager.GetObject("SCOREUs7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREUs8 {
            get {
                object obj = ResourceManager.GetObject("SCOREUs8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCOREUs9 {
            get {
                object obj = ResourceManager.GetObject("SCOREUs9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SoundApplauseLoud {
            get {
                return ResourceManager.GetStream("SoundApplauseLoud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SoundApplauseSoft {
            get {
                return ResourceManager.GetStream("SoundApplauseSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SoundApplauseWild {
            get {
                return ResourceManager.GetStream("SoundApplauseWild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SoundPlayCard {
            get {
                return ResourceManager.GetStream("SoundPlayCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SoundShuffleDeck {
            get {
                return ResourceManager.GetStream("SoundShuffleDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spades.
        /// </summary>
        internal static string SPADES {
            get {
                return ResourceManager.GetString("SPADES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPADESIMAGE {
            get {
                object obj = ResourceManager.GetObject("SPADESIMAGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
